
version: "3.8"
services:
  app:
    build: ./app
    container_name: hats-for-parties
    ports:
      - ${PORT}:${PORT}
    environment:
      - PORT=${PORT}
      - MONGODB_URI=mongodb://mongodb:27017
      - REDIS_URI=cache:6379
      # - REDIS_URL=redis://cache:6379
      - TOTAL_HATS=${TOTAL_HATS}
      - TOTAL_HATS_PER_PARTY=${TOTAL_HATS_PER_PARTY}
      - CLEANING_TIME_IN_SECONDS=${CLEANING_TIME_IN_SECONDS}
      - HATS_COLLECTION_NAME=${HATS_COLLECTION_NAME}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mongodb_container
  mongodb_container:
    image: mongo:latest
    container_name: mongodb
    environment:
      - TOTAL_HATS=${TOTAL_HATS}
      - DB_NAME=${DB_NAME}
      - HATS_COLLECTION_NAME=${HATS_COLLECTION_NAME}
    ports:
      - 27017:27017
    volumes:
      - ./mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  cache:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - 6379:6379
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache:/data
      
volumes:
  mongodb_data_container:
  cache:
    driver: local
